name: main

on:
  push:
    branches: [ "main" ]
  workflow_call:
    secrets:
      WAF_ACCESS_KEY_ID: 
        required: true
      WAF_SECRET_ACCESS_KEY:
        required: true
      IPSET_ID:
        required: true
      ROLE_TO_ASSUME:
        required: true
    
permissions:
  id-token: write
  contents: read
  deployments: write
    
jobs:

  deployment:  
    runs-on: ubuntu-latest
    environment: development
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.WAF_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.WAF_SECRET_ACCESS_KEY }}

    steps:
    - name: Add Public IP to Allow
      uses: iDVB/wafv2-allow-action@v1
      with:
        action: add
        ipset_id: ${{ secrets.IPSET_ID }}
        ipset_name: github_action_runners
        ipset_scope: REGIONAL
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
        aws-region: us-east-1
        
    - name: Sleep for 45 seconds
      run: sleep 45s
      shell: bash
    
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        fetch-depth: 0
    
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 14.19.3
        # cache: 'npm'

    - name: Install dependences
      run: npm i
      
    # - name: Run Deploy 
    #   run: npm run deploy -- -n mic -e dev 
    
    - name: Run Deploy 
      run: ./deploy.sh mic dev 

    - name: Remove Public IP from Allow
      if: always()
      uses: iDVB/wafv2-allow-action@v1
      with:
        action: remove
        ipset_id: ${{ secrets.IPSET_ID }}
        ipset_name: github_action_runners
        ipset_scope: REGIONAL
    
